(* parser.ml *)
    let show_token = function
      | LET            -> "LET"
      | IF             -> "IF"
      | ELSE           -> "ELSE"
      | THEN           -> "THEN"
      | PRINT          -> "PRINT"
      | FOR            -> "FOR"
      | WHILE          -> "WHILE"
      | DO             -> "DO"
      | DONE           -> "DONE"
      | REF            -> "REF"
      | IN             -> "IN"
      | AND            -> "AND"
      | OR             -> "OR"
      | NOT            -> "NOT"
      | ASSIGN         -> "ASSIGN"
      | DEREF          -> "DEREF"
      | PIPE           -> "PIPE"
      | LFLOOR         -> "LFLOOR"
      | RFLOOR         -> "RFLOOR"
      | SPEC_EQUAL     -> "SPEC_EQUAL"
      | PLUS           -> "PLUS"
      | MINUS          -> "MINUS"
      | TIMES          -> "TIMES"
      | DIV            -> "DIV"
      | MOD            -> "MOD"
      | EQUAL          -> "EQUAL"
      | CMP cmp        -> "CMP(" ^ (match cmp with
                             | Beq -> "Beq" | Bneq -> "Bneq"
                             | Blt -> "Blt" | Ble -> "Ble"
                             | Bgt -> "Bgt" | Bge -> "Bge") ^ ")"
      | LP             -> "LP"
      | RP             -> "RP"
      | LSQ            -> "LSQ"
      | RSQ            -> "RSQ"
      | COMMA          -> "COMMA"
      | COLON          -> "COLON"
      | NEWLINE        -> "NEWLINE"
      | BEGIN          -> "BEGIN"
      | END            -> "END"
      | EOF            -> "EOF"
      | IDENT s        -> "IDENT(" ^ s ^ ")"
      | CST (Cint i)   -> "CINT(" ^ string_of_int i ^ ")"
      | CST (Cbool b)  -> "CBOOL(" ^ string_of_bool b ^ ")"
      | CST (Cstring s)-> "CSTRING(" ^ String.escaped s ^ ")"
      | CST Cnone      -> "CNONE"
    